sudo: false
language: java
jdk:
- oraclejdk8
script:
- mvn install
deploy:
  provider: releases
  api_key:
    secure: Bm4Vg2pdciKH+o2W4Pv2DCU3VRLeoBpayQsqRC11BGhZ2c8KMkfqlHOtjcUisF3z683ZUZAsSJNT8N7CnonKF46e6YdWzNrvQxHODAxqEH3h/ZqjqS69PorMusKrsPddSzHZBvqkPTxBqz8xXAlmws08demwyzSxQ4X4G2mqeBmBYXml/zgEC4bMLK85Hh2lobVIkWUxfQTem/yrKgi/ODbINyGY0pBrPlEQkqwQx46z98/oVvH2RGC09ZHfb7ophkuyTlfZIktxBBrF6jY95DlNmadxPnWgYuht50rx71csCW5tyzOkA+VmYME1ODboI/MxBdhCGmjXOrjHt2sIVWmkgQ6aEVCVveeJXASMtqgxZT0YR7b7zMfVXlaRhDZ4DfaXdR5lWMeOGoGYiLDUTWxXrcADV8GY1oJTpFIe3NlXrfLYe70Ovy+xXIj03uA3Nd7IphgHI26s1RovpD0uk3tzY4uaa6rr2ZTJWe6gMddrriStsN08kfid/3knuR13HEcb5hCV3H6zLz/rgimdS9d0uoeIIjGP51+U7FklitlnCoIV6LAEZD20clyx/Tl+pqTHDwc0m4RfDF12jG4ZTZbGeyACX9uuhWjMyxfnKA9r2JmjOxMHBKTS2Zh2XcQkroP5YiZxX1PtdHM6vZKDC+e7dx6G/LfDdCvZHXXr0n4=
  file:
  - com.ifedorenko.p2browser.rcp/target/products/com.ifedorenko.p2browser.rcp-linux.gtk.x86.tar.gz
  - com.ifedorenko.p2browser.rcp/target/products/com.ifedorenko.p2browser.rcp-linux.gtk.x86_64.tar.gz
  - com.ifedorenko.p2browser.rcp/target/products/com.ifedorenko.p2browser.rcp-macosx.cocoa.x86_64.tar.gz
  - com.ifedorenko.p2browser.rcp/target/products/com.ifedorenko.p2browser.rcp-win32.win32.x86.zip
  - com.ifedorenko.p2browser.rcp/target/products/com.ifedorenko.p2browser.rcp-win32.win32.x86_64.zip
  on:
    repo: PizzaFactory/p2-browser
    tags: true
    all_branches: true
  skip_cleanup: true
